"use client";

import Navigation from "../components/NavBar";
import Footer from "../components/Footer";
import { Provider } from "react-redux";
import "../theme/globals.css";
import { Inter } from "next/font/google";
import { store } from "../store/store";

import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const path = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          {
            (path !== "/login" && path !== '/mycourses/id') && <Navigation />
          }
          {children}
          {
            path !== "/login" && <Footer />
          }
        </Provider>
      </body>
    </html>
  );
}
